In [1]:
import time
time.sleep(3)
print('Hello Whaa')

Hello Whaa


# This is a level 1 heading
## This is a level 2 heading
This is some plain text that forms a paragraph.
Add emphasis via **bold** and __bold__, or *italic* and _italic_.
Paragraphs must be separated by an empty line.
* Sometimes we want to include lists.
* Which can be indented.
1. Lists can also be numbered.
2. For ordered lists.
[It is possible to include hyperlinks](https://www.example.com)
Inline code uses single backticks: `foo()`, and code blocks use triple backticks:
```
import time
time.sleep(3)
print('Hello Whaa')
```
Or can be indented by 4 spaces:
foo()


In [2]:
import numpy as np
def square(x):
    return x * x

In [3]:
a=np.random.randint(1,30)
print('%d squared = %d'%(a,square(a)))

29 squared = 841


### PYTHON BASICS


In [2]:
import os
print (os.path.expanduser('~'))

# Start at Home ~

/Users/subhayuchakravarty


In [4]:
def extendList(val, list=[]):
    list.append(val)
    return list

list1 = extendList(10)
list2 = extendList(123,[])
list3 = extendList('a')
list4 = extendList('b')

# Weirdness - same list reused
print("list1 = %s" % list1)
print("list2 = %s" % list2)
print("list3 = %s" % list3)
print("list4 = %s" % list4)

list1 = [10, 'a', 'b']
list2 = [123]
list3 = [10, 'a', 'b']
list4 = [10, 'a', 'b']


In [6]:
def extendList2(val, list=None):
    if list==None:
        list=[]
    list.append(val)
    return list

list1 = extendList2(10)
list2 = extendList2(123,[])
list3 = extendList2('a')
list4 = extendList2('b')

# Weirdness - same list reused
print("list1 = %s" % list1)
print("list2 = %s" % list2)
print("list3 = %s" % list3)
print("list4 = %s" % list4)

list1 = [10]
list2 = [123]
list3 = ['a']
list4 = ['b']


In [7]:
# Email Reg Ex

import re
print(re.search(r"[0-9a-zA-Z.]+@[a-zA-Z]+\.(com|co\.in)$","micheal.pages@mp.com"))

<re.Match object; span=(0, 20), match='micheal.pages@mp.com'>


In [14]:
# No error in slic:ing
list = ['a', 'b', 'c', 'd', 'e']
print(list[12:])

[]


In [27]:
try:
    for i in range(0,55,10):
        print(i)
except:
    print('No good')
else:
    print('If no exceptions')
finally:
    print('All good')

0
10
20
30
40
50
If no exceptions
All good


In [31]:
#Immutability - var can be anything, original remains same
a='What'
b=a
a=a+a
print(a)
print(b)

WhatWhat
What


In [30]:
a=5
b=a
a=a+a
print(a)
print(b)

10
5


In [32]:
# Ord and Chr

print(ord("z"))
print(chr(122))

122
z


In [2]:
int(449/500)

0

In [2]:
data  = [
    (1, u'ASN', u'Mon', u'15:15:00'), 
    (2, u'ASN', u'Tue', u'15:15:00'), 
    (3, u'ASN', u'Wed', u'15:15:00'), 
    (5, u'ASN', u'Fri', u'15:15:00'), 
    (7, u'ASN', u'Sun', u'15:15:00'), 
    (15, u'ASN', 'Reminder', '2014-05-26 15:29'), 
    (16, u'ASN', u'Mon', u'15:15:00'), 
    (17, u'ASN', u'Tue', u'15:15:00'), 
    (18, u'ASN', u'Wed', u'15:15:00'), 
    (19, u'ASN', u'Fri', u'15:15:00')
]

In [3]:
uniq = {d[1:]:d for d in data}
uniq = uniq.values()

In [4]:
uniq

dict_values([(16, 'ASN', 'Mon', '15:15:00'), (17, 'ASN', 'Tue', '15:15:00'), (18, 'ASN', 'Wed', '15:15:00'), (19, 'ASN', 'Fri', '15:15:00'), (7, 'ASN', 'Sun', '15:15:00'), (15, 'ASN', 'Reminder', '2014-05-26 15:29')])

In [5]:
trips=[(-1, -1, 2), (1, -1, 0), (0, -1, 1), (2, -1, -1)]



In [6]:
d={tri[0:3]:tri for tri in trips}
d

{(-1, -1, 2): (-1, -1, 2),
 (1, -1, 0): (1, -1, 0),
 (0, -1, 1): (0, -1, 1),
 (2, -1, -1): (2, -1, -1)}

In [14]:
up=2147483647
down=1
temp=0
count=0
for i in range(31, -1, -1):
    print(temp,(down<<i),count)
    if (temp + (down << i) <= up):
        temp += down << i
        count |= 1 << i



0 2147483648 0
0 1073741824 0
1073741824 536870912 1073741824
1610612736 268435456 1610612736
1879048192 134217728 1879048192
2013265920 67108864 2013265920
2080374784 33554432 2080374784
2113929216 16777216 2113929216
2130706432 8388608 2130706432
2139095040 4194304 2139095040
2143289344 2097152 2143289344
2145386496 1048576 2145386496
2146435072 524288 2146435072
2146959360 262144 2146959360
2147221504 131072 2147221504
2147352576 65536 2147352576
2147418112 32768 2147418112
2147450880 16384 2147450880
2147467264 8192 2147467264
2147475456 4096 2147475456
2147479552 2048 2147479552
2147481600 1024 2147481600
2147482624 512 2147482624
2147483136 256 2147483136
2147483392 128 2147483392
2147483520 64 2147483520
2147483584 32 2147483584
2147483616 16 2147483616
2147483632 8 2147483632
2147483640 4 2147483640
2147483644 2 2147483644
2147483646 1 2147483646


### WTF is this code doing?

In [2]:
up=1e8
down=1
temp=0
count=0
for i in range(8, -1, -1):
    print(temp,(down<<i),count)
    if (temp + (down << i) <= up):
        temp += down << i
        count |= 1 << i

0 256 0
256 128 256
384 64 384
448 32 448
480 16 480
496 8 496
504 4 504
508 2 508
510 1 510


In [63]:
(2**9980899 - (3*9980899 - 1))%3*9980899

0

In [66]:
(2 >> 9980898)%9980899

0

In [17]:
(1<<1008000)%1008001

1

In [19]:
checkPrime(1008001)

True

In [18]:
import math
def checkPrime(out):
    rem=-1
    if out==1:
        return False
    if out==2:
        return True
    if out%2==0:
        return False
    
    if out<1000000:
        for div in range(3,int(math.sqrt(out))+1,2):
            if out%div==0:
                return False
    else:
        x=(1<<(out-1))%out
        if x!=1:
            return False
    return True

In [1]:
float(1/2147483648)

4.656612873077393e-10

In [1]:
import count as cp

[[1.0401014  3.79275213 3.489087   1.01277312]] 15806.69023655018
[[1.04523431 4.13809326 3.78489069 1.01795507]] 14646.43122540586
[[1.0461177  4.18601872 3.81417041 1.02221441]] 14628.107743358116
[[1.04648455 4.19779734 3.81106719 1.02636153]] 14626.649145035317
[[1.0467885  4.20517869 3.80403401 1.03049489]] 14625.441207795526
[[1.04708467 4.212021   3.79652849 1.03462647]] 14624.238582436523
[[1.04737976 4.21879312 3.78897079 1.03875772]] 14623.03764330652
[[1.04767459 4.22555204 3.78141198 1.04288881]] 14621.83833435417
[[1.04796926 4.23230469 3.77385824 1.04701977]] 14620.64065224532
[[1.04826378 4.2390519  3.76631032 1.0511506 ]] 14619.444594428209
[[1.04855815 4.24579379 3.75876833 1.0552813 ]] 14618.250158366556
[[1.04885237 4.25253037 3.75123225 1.05941187]] 14617.057341528196
[[1.04914644 4.25926165 3.7437021  1.06354232]] 14615.866141384935
[[1.04944036 4.26598763 3.73617786 1.06767263]] 14614.676555412536
[[1.04973413 4.27270832 3.72865953 1.07180282]] 14613.488581090696


[[ 1.21776049  7.76152205 -0.17651183  3.80560194]] 14081.406522391255
[[ 1.21797652  7.76548656 -0.18095317  3.8096616 ]] 14080.886960216785
[[ 1.21819245  7.76944795 -0.18539101  3.81372117]] 14080.367964261673
[[ 1.2184083   7.77340619 -0.18982536  3.81778066]] 14079.849533643674
[[ 1.21862406  7.77736131 -0.19425621  3.82184006]] 14079.331667481922
[[ 1.21883974  7.78131331 -0.19868357  3.82589937]] 14078.814364896914
[[ 1.21905532  7.78526218 -0.20310745  3.8299586 ]] 14078.297625010522
[[ 1.21927081  7.78920792 -0.20752784  3.83401775]] 14077.781446946012
[[ 1.21948622  7.79315055 -0.21194474  3.83807681]] 14077.265829827991
[[ 1.21970154  7.79709006 -0.21635817  3.84213578]] 14076.750772782465
[[ 1.21991677  7.80102645 -0.22076812  3.84619467]] 14076.236274936782
[[ 1.22013192  7.80495974 -0.22517459  3.85025347]] 14075.722335419658
[[ 1.22034697  7.80888991 -0.22957759  3.85431219]] 14075.208953361185
[[ 1.22056194  7.81281697 -0.23397713  3.85837082]] 14074.696127892805
[[ 1.2

[[ 1.28138044  8.86106522 -1.40884752  5.07232927]] 13942.457752969662
[[ 1.28157185  8.86415925 -1.41231704  5.07636435]] 13942.078549227434
[[ 1.28176319  8.86725082 -1.41578382  5.08039936]] 13941.699693187493
[[ 1.28195446  8.87033994 -1.41924786  5.0844343 ]] 13941.321184309165
[[ 1.28214566  8.87342661 -1.42270917  5.08846916]] 13940.943022052581
[[ 1.28233679  8.87651083 -1.42616774  5.09250396]] 13940.565205878751
[[ 1.28252785  8.87959261 -1.42962359  5.09653868]] 13940.18773524951
[[ 1.28271884  8.88267194 -1.4330767   5.10057333]] 13939.810609627522
[[ 1.28290976  8.88574883 -1.43652709  5.10460791]] 13939.433828476314
[[ 1.28310062  8.88882328 -1.43997476  5.10864242]] 13939.057391260252
[[ 1.2832914   8.89189529 -1.4434197   5.11267685]] 13938.681297444511
[[ 1.28348212  8.89496487 -1.44686192  5.11671122]] 13938.305546495141
[[ 1.28367277  8.89803201 -1.45030143  5.12074551]] 13937.93013787899
[[ 1.28386334  8.90109672 -1.45373822  5.12477973]] 13937.555071063758
[[ 1.284

[[ 1.36943343 10.13814648 -2.84225061  7.08162488]] 13786.911253135291
[[ 1.36959603 10.14022479 -2.84458616  7.08562825]] 13786.653017231285
[[ 1.36975858 10.14230145 -2.84691987  7.08963156]] 13786.394941341003
[[ 1.36992108 10.14437644 -2.84925172  7.09363481]] 13786.137025217091
[[ 1.37008354 10.14644978 -2.85158172  7.09763801]] 13785.879268612625
[[ 1.37024595 10.14852147 -2.85390988  7.10164115]] 13785.621671281035
[[ 1.37040832 10.1505915  -2.85623619  7.10564424]] 13785.364232976151
[[ 1.37057063 10.15265987 -2.85856065  7.10964727]] 13785.106953452178
[[ 1.3707329  10.1547266  -2.86088327  7.11365025]] 13784.849832463711
[[ 1.37089512 10.15679167 -2.86320405  7.11765317]] 13784.59286976574
[[ 1.3710573  10.1588551  -2.86552298  7.12165603]] 13784.33606511362
[[ 1.37121943 10.16091688 -2.86784008  7.12565884]] 13784.079418263087
[[ 1.37138151 10.16297701 -2.87015534  7.12966159]] 13783.822928970272
[[ 1.37154355 10.1650355  -2.87246876  7.13366429]] 13783.566596991694
[[ 1.371

[[ 1.44553353 10.99475257 -3.80622256  9.07682298]] 13673.491469354143
[[ 1.44567654 10.99614398 -3.80779122  9.08080126]] 13673.289049413437
[[ 1.44581953 10.99753426 -3.80935863  9.08477949]] 13673.086703629728
[[ 1.44596248 10.99892342 -3.81092479  9.08875768]] 13672.884431889865
[[ 1.4461054  11.00031146 -3.8124897   9.09273582]] 13672.682234080874
[[ 1.4461054  11.00031146 -3.8124897   9.09273582]] 13672.682234080874


In [2]:
inpu=[1.0, 66.0,56.0,0.1]

In [4]:
print(ct2.getNewPrediction(inpu)[0])
print(ct2.getOldPrediction(inpu))

486.2983732969314
5447.857674748


In [2]:
cp.predictRow(20)

Actual:  [732]
Predicted:  [528.20244556]


In [1]:
import pandas as pd

In [15]:
x=pd.read_csv('weather.csv', header=None)

In [16]:
x.head()


0   1     2
0   0   1  2.00
1  67  63  0.08
2  67  63  0.60
3  67  63  0.08
4  68  63  0.40

In [13]:
x.shape

(36, 3)

In [12]:
x=x.append([[50,40,0.02]], ignore_index=True)
x.tail()

0   1      2
31  71  70  0.010
32  73  71  0.060
33  55  50  0.002
34  55  50  0.002
35  50  40  0.020

In [14]:
x.to_csv('weather.csv', index=False, header=False)

In [11]:
int('-0',16)

0

In [1]:
import nltk
from nltk import word_tokenize
from nltk.util import ngrams
from collections import Counter
text = "This camera produces awesome pictures."

token = nltk.word_tokenize(text)
bigrams = ngrams(token,2)
trigrams = ngrams(token,3)

In [4]:
for x in bigrams:
    print(x)

('This', 'camera')
('camera', 'produces')
('produces', 'awesome')
('awesome', 'pictures')
('pictures', '.')


In [5]:
for x in trigrams:
    print(x)

('This', 'camera', 'produces')
('camera', 'produces', 'awesome')
('produces', 'awesome', 'pictures')
('awesome', 'pictures', '.')


In [3]:
a=[1,6,4,5,5,3,7,8,2,9,10,12,11,10,12,12]
m=max(a)

In [6]:
max([i for i, j in enumerate(a) if j == m])

12